apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
      - name: web-app
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-svc
spec:
  selector:
    app: simple-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
